version: '3.8'

services:
  api:
    container_name: air_api
    build: ./services/api
    command: uvicorn main:app --host 0.0.0.0 --port 80
    ports:
      - 8100:80
    volumes:
      - ./services/api:/api
    env_file:
      - ./services/api/.env.dev
    depends_on:
      db:
        condition: service_healthy

  app:
    container_name: air_app
    build: ./services/air_app
    command: python wsgi.py
    ports:
      - 800:5000
    volumes:
      - ./services/air_app:/app
    env_file:
      - ./services/air_app/.env.dev
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:14.5-alpine
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=airdb
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:
