version: '3.8'

services:
  api:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8100 --reload
    ports:
      - 8100:8100
    volumes:
      - ./services/api:/api
    env_file:
      - ./services/api/.env.dev
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:14.5-alpine
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=airdb
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:
